import type { Application } from "express-serve-static-core";

import AddressRouter from "./address.js";
import ItemAdminRouter from "./admin/itemAdmin.js";
import UserAdminRouter from "./admin/userAdmin.js";
import authRouter from "./auth.js";
import BankAccountRouter from "./bankAccount.js";
import BanksRouter from "./banks.js";
import BranchesRouter from "./branches.js";
import BrandsRouter from "./brands.js";
import CartRouter from "./cart.js";
import CategoriesRouter from "./categories.js";
import CommentRouter from "./comment.js";
import CommentLikeRouter from "./commentLike.js";
import CommentReportRouter from "./commentReport.js";
import DeliveryRouter from "./delivery.js";
import FollowRouter from "./follow.js";
import IdCardRouter from "./idCard.js";
import InquiryRouter from "./inquiry.js";
import ItemLikeRouter from "./itemLike.js";
import ItemReportRouter from "./itemReport.js";
import ItemsRouter from "./items.js";
import NameRouter from "./name.js";
import NotificationRouter from "./notification.js";
import OrdersRouter from "./orders.js";
import PointsHistoryRouter from "./pointsHistory.js";
import PurchaseSessionRouter from "./purchaseSession.js";
import ReferenceCodeRouter from "./referenceCode.js";
import SaleRouter from "./sale.js";
import SearchRouter from "./search.js";
import ShopInfoRouter from "./shopInfo.js";
import ShopInfoEditRouter from "./shopInfoEdit.js";
import SuggestWordsRouter from "./suggestWords.js";
import TransferRouter from "./transfer.js";
import UriagekinHistoryRouter from "./uriagekinHistory.js";
import usersRouter from "./users.js";
import UsersMeItemsRouter from "./users/me/items.js";
import VideoRouter from "./video.js";
import WatchHistoryRouter from "./watchHistory.js";

export const registerRoutes = (app: Application) => {
    app.use("/api/user", usersRouter);
    app.use("/api/users/me/items", UsersMeItemsRouter);
    app.use("/api/auth", authRouter);
    app.use("/api/items", ItemsRouter);
    app.use("/api/item-like", ItemLikeRouter);
    app.use("/api/address", AddressRouter);
    app.use("/api/bank-account", BankAccountRouter);
    app.use("/api/banks", BanksRouter);
    app.use("/api/branches", BranchesRouter);
    app.use("/api/brands", BrandsRouter);
    app.use("/api/cart", CartRouter);
    app.use("/api/categories", CategoriesRouter);
    app.use("/api/comment-like", CommentLikeRouter);
    app.use("/api/comment-report", CommentReportRouter);
    app.use("/api/comment", CommentRouter);
    app.use("/api/delivery", DeliveryRouter);
    app.use("/api/follow", FollowRouter);
    app.use("/api/id-card", IdCardRouter);
    app.use("/api/inquiry", InquiryRouter);
    app.use("/api/name", NameRouter);
    app.use("/api/notification", NotificationRouter);
    app.use("/api/orders", OrdersRouter);
    app.use("/api/points-history", PointsHistoryRouter);
    app.use("/api/purchase-session", PurchaseSessionRouter);
    app.use("/api/reference-code", ReferenceCodeRouter);
    app.use("/api/item-report", ItemReportRouter);
    app.use("/api/sale", SaleRouter);
    app.use("/api/search", SearchRouter);
    app.use("/api/shop-info", ShopInfoRouter);
    app.use("/api/shop-info-edit", ShopInfoEditRouter);
    app.use("/api/suggest-words", SuggestWordsRouter);
    app.use("/api/transfer", TransferRouter);
    app.use("/api/uriagekin-history", UriagekinHistoryRouter);
    app.use("/api/video", VideoRouter);
    app.use("/api/watch-history", WatchHistoryRouter);
    app.use("/api/admin/items", ItemAdminRouter);
    app.use("/api/admin/user", UserAdminRouter);
};
